-- Script para crear la tabla de atajos de servicios rápidos en Supabase
-- Puedes ejecutar este script en el editor SQL de Supabase (SQL Editor)

CREATE TABLE IF NOT EXISTS public.servicios_rapidos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre TEXT NOT NULL UNIQUE,
  precio_sugerido NUMERIC(10,2) DEFAULT 0.00,
  color TEXT DEFAULT 'purple',
  creado_en TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Habilitar Seguridad a Nivel de Fila (Row Level Security - RLS)
ALTER TABLE public.servicios_rapidos ENABLE ROW LEVEL SECURITY;

-- Crear Políticas de Acceso Público para el Punto de Venta Local (POS)
CREATE POLICY "Permitir lectura pública de servicios_rapidos" 
  ON public.servicios_rapidos 
  FOR SELECT 
  USING (true);

CREATE POLICY "Permitir inserción pública de servicios_rapidos" 
  ON public.servicios_rapidos 
  FOR INSERT 
  WITH CHECK (true);

CREATE POLICY "Permitir actualización pública de servicios_rapidos" 
  ON public.servicios_rapidos 
  FOR UPDATE 
  USING (true);

CREATE POLICY "Permitir eliminación pública de servicios_rapidos" 
  ON public.servicios_rapidos 
  FOR DELETE 
  USING (true);

-- Insertar atajos por defecto en la base de datos para comenzar inmediatamente
INSERT INTO public.servicios_rapidos (nombre, precio_sugerido, color) VALUES
  ('Impresión BN', 2.00, 'purple'),
  ('Impresión Color', 5.00, 'indigo'),
  ('Copia BN', 2.00, 'emerald'),
  ('Copia Color', 5.00, 'pink'),
  ('Escaneo / PDF', 10.00, 'amber'),
  ('Trámite de Acta', 50.00, 'rose'),
  ('Uso de Computadora', 15.00, 'cyan'),
  ('Recibo de Luz / Pago', 10.00, 'teal'),
  ('Servicio General', 0.00, 'violet')
ON CONFLICT (nombre) DO NOTHING;
